---

- name: Docker - Ensure repository key is installed
  apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      state: present

- name: Docker - Ensure docker registry is available
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main'
    state: present
    update_cache: yes

- name: Docker - Ensure docker and dependencies are installed
  apt: name=docker-engine update_cache=yes

- name: Docker - Add users to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: true
  with_items: "{{ docker_users }}"
  when: docker_users
  notify: ["restart docker"]