---

- name: Ensure docker-compose is installed and available
  get_url:
    url : https://github.com/docker/compose/releases/download/1.21.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 'a+x'