---

- name: add openjdk-r ppa
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: present
    update_cache: true

- name: OpenJDK - Installing Java
  apt: name="{{ item }}" state=present
  with_items:
    - openjdk-8-jdk
    - ca-certificates
  become: true

- name: Fix "trustAnchors parameter must be non-empty" issue
  command: "{{item}}"
  with_items:
    - dpkg --purge --force-depends ca-certificates-java
    - apt-get install ca-certificates-java
  become: true
