---
- name: OpenJDK - Installing Pre-Reqs
  apt: name="{{ item }}" state=present
  with_items:
    - apt-transport-https
    - software-properties-common
  become: true


- name: OpenJDK - Adding OpenJDK PPA
  apt_repository: repo="ppa:openjdk-r/ppa"  state=present
  become: true

- name: OpenJDK - Installing Java
  apt: name="openjdk-8-jdk" state=present
  become: true
