---

- name: Oracle Java - Add webupd8 ppa
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: Oracle Java - apt-get update
  apt: update_cache=yes
  become: true

- name: Oracle Java - Auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  become: true

- name: Oracle Java - Install java8
  shell: apt-get install -y oracle-java8-installer ca-certificates
  become: true

